export * from './Dashboard.section';
export * from './EmployeeView';
export * from './Leads.section';
export * from './ManageAttributes.section';
export * from './ManageAwbGeneratedPending.section';
export * from './ManageBiDraftIssued.section';
export * from './ManageBiIssued.section';
export * from './ManageBookingIssue.section';
export * from './ManageBranchDetails';
export * from './ManageBRC.section';
export * from './ManageCompanyDetail.section';
export * from './ManageContainersUnderLoading.section';
export * from './ManageContainerType.section';
export * from './ManageCurrencyType.section';
export * from './ManageCustomers.section';
export * from './ManageCustomerType';
export * from './ManageDeliveryTerms.section';
export * from './ManageDocumentSendDhlSubmitted.section';
export * from './ManageFinalAmountToPay.section';
export * from './ManageForwarding.section';
export * from './ManageLOCATION.section';
export * from './ManageInvoiceGenerated.section';
export * from './ManageOrderAccepted.section';
export * from './ManageOrderCompletedPending.section';
export * from './ManageOrderUnderProcess.section';
export * from './ManagePackagingType.section';
export * from './ManagePaperType.section';
export * from './ManagePaymentReceived_LCReceived.section';
export * from './ManagePaymentTerms.section';
export * from './ManagePIConfirmedbyCustomer.section';
export * from './ManagePINumber';
export * from './ManagePO.section';
export * from './ManagePOIssued.section';
export * from './ManagePortDischarge.section';
export * from './ManageProductionStatus.section';
export * from './ManageProfile.section';
export * from './ManageTerritory.section';
export * from './ManageTrackingStatus.section';
export * from './ManageTrackingStatusCustomer.section';
export * from './ManageTypeOfPackaging.section';
export * from './ManageUnit.section';
export * from './PieChart';
export * from './RolePermission';
export * from './TrackingStatus.section';
export * from './VisitorCompany.section';
export * from './VisitorDetails.section';
export * from "./ManageFloor.section"
export * from "./ManageAdminTypeOfVisitor.section"
export * from "./ManageAdminReasonType.section"
export * from "./ManageAdminDVMServerName.section"
export * from "./ManageAdminEBIServerName.section"
export * from "./ManageAdminEmergencyType.section"
export * from "./ManageAdminEmergencyClosureBy.section"
export * from "./ManageAdminShift.section"
export * from "./ManageAdminRoute.section"
export * from "./ManageAdminverifiedBy.section"
export * from "./ManageAdminMaritalStatus.section"
export * from "./ManageAdminBloodGroup.section"
export * from "./ManageAdminEmployeeType.section"
export * from "./ManageAdminGender.section"
export * from "./ManageAdminEventType.section"
export * from "./ManageAdminCourierName.section"
export * from "./ManageAdminPBType.section"
export * from "./ManageAdminIncidentType.section"
export * from "./ManageAdminHanderOverByName.section"
export * from "./ManageAdminVehicleType.section"
export * from  "./ManageAdminVisitPurpose.section"
export * from "./EmployeePermission"